
apiVersion: v1
kind: Namespace
metadata:
  name: urlshortener-staging
---
apiVersion: v1
kind: Service
metadata:
  name: urlshortener
  namespace: urlshortener-staging
spec:
  ports:
  - port: 8181
    targetPort: 8181
  selector:
    app: urlshortener
  sessionAffinity: ClientIP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: glob:dev-*
  name: urlshortener
  namespace: urlshortener-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
      name: urlshortener
    spec:
      containers:
      - image: versxisto/urlshortener:latest
        imagePullPolicy: IfNotPresent
        name: urlshortener
        ports:
        - containerPort: 8181
          protocol: TCP